### ISSUE TITLE
Построить деревья целей по целям стейкхолдеров

### ISSUE THREAD

**Issue by XeniaWorontsova** [Students-of-the-city-of-Kostroma/Ray-of-hope#143]
Epic #156 
https://drive.google.com/open?id=1Ij-aThmSJHgzoYyEH7FV2txws8nf3RP-

- [x] дерево целей благотворительной организации

- [x] дерево целей человека, попавшего в тяжелую жизненную ситуацию

- [x] дерево целей неравнодушных граждан

- [x] дерево целей волонтеров

- [x] дерево целей юридических лиц

**Comment by KharlamovaAlexandra** [comment]
почему не стоит сложность и приоритет?

**Comment by XeniaWorontsova** [comment]
> почему не стоит сложность и приоритет?

Потому что я не понимаю Ваши приоритеты и сложность

**Comment by KharlamovaAlexandra** [comment]
Суть приоритетов подписана прямо в самих лейблах.
Сложность относительна первоначальной задачи со сложностью 1. Ты ставишь во сколько раз сложнее твоя задача, чем самая простая на проекте

**Comment by XeniaWorontsova** [comment]
> Суть приоритетов подписана прямо в самих лейблах.
> Сложность относительна первоначальной задачи со сложностью 1. Ты ставишь во сколько раз сложнее твоя задача, чем самая простая на проекте

Как человеку, который работает с приоритетами High, Low и тд - мне сложно
А сложность вообще просто сложно оценить

**Comment by YuriSilenok** [comment]
> > Суть приоритетов подписана прямо в самих лейблах.
> > Сложность относительна первоначальной задачи со сложностью 1. Ты ставишь во сколько раз сложнее твоя задача, чем самая простая на проекте
> 
> Как человеку, который работает с приоритетами High, Low и тд - мне сложно
> А сложность вообще просто сложно оценить

В JIRA действительно есть приоритеты  High, Low и тд, 
Думаю названия из JIRA нужно внести в описание лейблов, 
для этого нужно их сопоставить, типа
- PR1 - Low

Сделай пожалуйста такое сопоставление в комментариях этой задачи.

**Comment by KharlamovaAlexandra** [comment]
@XeniaWorontsova  Состояние задачи?

**Comment by XeniaWorontsova** [comment]
Псотроено дерево целей для благотворительной организации

**Comment by YuriSilenok** [comment]
Не могу из этой задачи перейти к документу с Деревом целей.

**Comment by XeniaWorontsova** [comment]
@YuriSilenok 
Хм, я смогла перейти. Или ссылки не было и ее кто-то добавил?

**Comment by YuriSilenok** [comment]
Возможно у меня лыжи не едут. Сейчас смог открыть ссылку которая в описании задачи с большой диаграммой.
